pyapp-kit/psygnal

psygnal/__init__.py, psygnal/_signal.py, tests/test_psygnal.py
allow connect decorator to accept kwargs
=> connect decorator, optional args

psygnal/_signal.py, setup.cfg, typesafety/test_signal.yml
Adding a few more tests for our type stubs
=> Add more typing tests

.pre-commit-config.yaml, psygnal/_signal.py, tests/test_psygnal.py
=> add __call__ as alias for `emit` on SignalInstance

.github/workflows/benchmark.yml, .gitignore, asv.conf.json, benchmarks/benchmarks.py
thanks @jaimergp for the fantastic [blog post](https://labs.quansight.org/blog/2021/08/github-actions-benchmarks/) on getting this setup
=> add asv benchmark to CI

README.md, psygnal/__init__.py, psygnal/_signal.py, setup.py, tests/test_psygnal.py
=> enable uncompiled import with PSYGNAL_UNCOMPILED env var 

psygnal/__init__.py, psygnal/_signal.py, setup.cfg, typesafety/test_signal.yml
just moving a few things around, and tweaking typing in a few places
=> Misc-typing and minor reorg

.github/workflows/ci.yml, psygnal/__init__.py, psygnal/_throttler.py, setup.cfg, tests/test_throttler.py
implements a throttler that could be used in #54
=> add Throttler class

.github/workflows/ci.yml, .readthedocs.yaml, docs/API/model.md, docs/API/proxy.md, docs/API/throttler.md, docs/index.md, docs/requirements.txt, docs/usage.md, mkdocs.yml, psygnal/_evented_model.py, psygnal/_group.py, psygnal/_signal.py, psygnal/containers/__init__.py, psygnal/containers/_evented_list.py, psygnal/containers/_evented_proxy.py, psygnal/containers/_evented_set.py, psygnal/containers/_selectable_evented_list.py, psygnal/containers/_selection.py, psygnal/utils.py, setup.cfg, tests/containers/test_evented_proxy.py
also adds CI to test that docs build without warning, and updates some docstryings.
This PR also adds docs for evented Proxy, and makes `EventedCallableObjectProxy` a public export
=> add readthedocs config, make EventedCallableObjectProxy public

.pre-commit-config.yaml, psygnal/_evented_model.py, psygnal/_group.py, psygnal/_signal.py, setup.cfg, tests/containers/test_evented_list.py, tests/containers/test_evented_proxy.py
updating pre-commit config a bit, adding a few more flake8 plugins
=> ci: flake8 updates

pyproject.toml, src/psygnal/_group.py, src/psygnal/containers/_evented_list.py
~griffe 0.22.0 has an issue with psygnal~ ... had some unparseable docstring types
=> docs: fix docs build

src/psygnal/_evented_model.py, tests/test_evented_model.py
the `EventedModel` allows for adding `allow_property_setters` to the Config, to enable support for `@property.setter` syntax in a BaseModel.
This PR fixes a bug wherein the setter methods are not inherited properly by subclasses
=> fix: fix inheritance of property setters

src/psygnal/_group.py
uses `__init_subclass__` rather than metaclass for `SignalGroup`
=> refactor: don't use metaclass for signal group

src/psygnal/_signal.py
gets rid of the `PartialMethodMeta.__instancecheck__` approach in favor of a simple function with a `TypeGuard`
=> refactor: remove PartialMethodMeta for TypeGuard func

docs/API/containers.md, docs/API/evented.md, docs/API/utilities.md, docs/dataclasses.md, mkdocs.yml, pyproject.toml, src/psygnal/_evented_decorator.py, src/psygnal/_group_descriptor.py
adds the `SignalGroupDescriptor` to the docs.
=> docs: update evented docs to descript SignalGroupDescriptor

src/psygnal/_signal.py, src/psygnal/utils.py, tests/containers/test_evented_proxy.py, tests/test_utils.py
adds the ability to spy on *all* events, regardless of the object emitting
=> feat: improved `monitor_events`

.pre-commit-config.yaml, pyproject.toml, src/psygnal/_throttler.py, src/psygnal/_throttler.pyi, tests/test_throttler.py
this adds _throttler.py to the files compiled by mypyc.  It also improves typing by retaining the function signature inputs on the function passed to debounced/throttled (this required using a pyi file, since mypyc doesn't support ParamSpec)
=> feat: compile throttler module, improve typing

.github/workflows/test.yml, CHANGELOG.md, Makefile, pyproject.toml, typesafety/test_group.yml, typesafety/test_signal.yml, typesafety/test_utils.yml
=> test: add back typesafety tests

.github/workflows/test.yml, pyproject.toml, src/psygnal/_weak_callback.py, tests/test_psygnal.py, tests/test_weak_callable.py
=> feat: Support toolz

src/psygnal/_evented_model.py, tests/test_evented_model.py
=> fix: fix duplicated derived events

pyproject.toml, src/psygnal/__init__.py, src/psygnal/_dataclass_utils.py, src/psygnal/_evented_model_v1.py, src/psygnal/_group_descriptor.py, src/psygnal/_queue.py, src/psygnal/containers/__init__.py, src/psygnal/containers/_evented_set.py, tests/test_dataclass_utils.py, tests/test_evented_decorator.py, tests/test_evented_model.py, tests/test_group_descriptor.py
=> Fix imports of typing extensions

.github/workflows/test.yml, pyproject.toml
this uses the test workflows provided by [pyapp-kit/workflows](https://github.com/pyapp-kit/workflows)
=> ci: use reusable ci workflow

.github/workflows/test.yml, pyproject.toml, src/psygnal/__init__.py, src/psygnal/_dataclass_utils.py, src/psygnal/_group.py, src/psygnal/_group_descriptor.py, src/psygnal/_signal.py, src/psygnal/_weak_callback.py, src/psygnal/containers/_evented_proxy.py, src/psygnal/qt.py, tests/test_evented_model.py, tests/test_psygnal.py
v0.9.x will be the last version range to support python 3.7
=> Drop python 3.7

.pre-commit-config.yaml, benchmarks/benchmarks.py, src/psygnal/_signal.py, src/psygnal/containers/_evented_set.py, tests/test_psygnal.py
In this PR I have added an option for the combiner function to consume the whole list of tuples at once.
=> perf: Fixing performance of evented set

.github/workflows/benchmark.yml, .github/workflows/test.yml, .pre-commit-config.yaml, CHANGELOG.md, asv.conf.json, pyproject.toml, src/psygnal/_dataclass_utils.py, src/psygnal/_queue.py, src/psygnal/_signal.py
fixes the issue that was causing us to pin mypyc for builds
also closes #371
=> chore: Update mypyc build

.pre-commit-config.yaml, pyproject.toml, src/psygnal/containers/_evented_dict.py, src/psygnal/containers/_evented_list.py, src/psygnal/containers/_evented_set.py, tests/test_evented_model.py
=> fix: fix evented container pydantic serialization
