pyapp-kit/psygnal

- README.md
- psygnal/_signal.py
- tests/test_psygnal.py
turns out `inspect.signature(print)` doesn't always work, (and probably other things), so this catches those cases and warns
> Catch inspection failures on connect (e.g. `print`), and improve maxargs syntax

- psygnal/_signal.py
- tests/test_qtbot.py
This adds a test that demonstrates that pytest-qt can actually be used to test Signals from psygnal. (psygnal will never use Qt, but it's cool that you can still use stuff like `waitSignals` from qtbot)
> test working with qtbot

- Makefile
- psygnal/_signal.py
- tests/test_psygnal.py
fixes #27 
not sure if this will break other (unanticipated) things, so going to let this sit for a bit
h/t @Czaki
> Set SignalInstances directly as attributes on objects (fix bug with hashable signal holders)

- .gitignore
- Makefile
- psygnal/_signal.py
- tests/test_psygnal.py
In this PR there is fix for selection of wrong select (most common case is decorator which not mock `__name__`)
Also partial mathods are unwrapped and weakref to base object is keep.
_edit_: ... an example of things being fixed here:
```py
def deco(fun):
def _fun(*args):
fun(*args)
return _fun
class MyObj:
@deco
def method(self, a: int): ...
assigned_func = lambda self, a: None
class Emitter:
changed = Signal(int)
e = Emitter()
obj = MyObj()
e.changed.connect(obj.method)
e.changed.connect(obj.assigned_func)
e.changed.connect(partial(obj.method))
```
> Avoid holding strong reference to decorated and partial methods

- psygnal/_signal.py
- tests/test_psygnal.py
> add connect/disconnect_settattr

- benchmarks/benchmarks.py
catches attr error with `connect_setattr` in older benchmarks
> deal with changing API in benchmarks

- psygnal/utils.py
- setup.cfg
- setup.py
- tests/test_psygnal.py
- tests/test_utils.py
simple helper context to print or otherwise collect/log events emitted within the context:
```python
from psygnal.utils import debug_events
with debug_events(some_object_with_signals):
...  # do something that will cause events
```
it takes an optional keyword argument `logger` that handles reporting the events, which, by default, simply prints events to stdout
```py
def _default_event_logger(event_name: str, args: Tuple[Any, ...]) -> None:
print(f"{event_name}.emit{args!r}")
```
> add debug_events util

- psygnal/_group.py
- psygnal/_signal.py
- tests/test_group.py
- tests/test_psygnal.py
Some improvements to the recently added SignalGroup.
Adds the `with group.blocked():` context manager, and better inherits the machinery from SignalInstance to prevent holding strong refs
> add SignalGroup blocked context manager, improve inheritance, and fix strong refs

- psygnal/containers/__init__.py
- psygnal/containers/_evented_proxy.py
- setup.cfg
- tests/containers/test_evented_proxy.py
`from psygnal.containers import EventedObjectProxy`
Create a proxy of `target` that includes an `events` SignalGroup
The events available at target.events include:
attribute_set = Signal(str, object)
attribute_deleted = Signal(str)
item_set = Signal(object, object)
item_deleted = Signal(object)
in_place = Signal(str, object)
and if `target` is callable:
called = Signal(tuple, dict)
> Add EventedObjectProxy

- .github/workflows/ci.yml
run magicgui tests during CI.  Though magicgui will no longer be trying to subclass psygnal anymore after magicgui 0.4.0, this will just make sure that any psygnal changes don't break magicgui (such as the _normalize_slot Attribute error in magicgui < 0.3.6 with psygnal >= 0.3.0
> add a magicgui test to CI

- psygnal/_signal.py
- tests/test_psygnal.py
An object __repr__ can, in some cases, evaluate or run code.   So we shouldn't use it as means of determining whether something is a bound qt signal instance `emit` method
> Don't use `repr(obj)` when checking for Qt emit signature

- setup.py
this checks the cython version at buildtime, and disables containers (which require newer cython's generic type support)
> work with older cython

- psygnal/_group.py
In the last release, I tried to exempt some of the container stuff that breaks without the newest cython from cythonize.  But, named tuple was still failing.  This just uses a custom object instead of typing.NamedTuple
> Used custom tuple for cython compatibility

- .pre-commit-config.yaml
- psygnal/containers/__init__.py
- psygnal/containers/_evented_dict.py
- tests/containers/test_evented_dict.py
This is pretty much a straight port of the `EventedDict` @lukasz-migas added to napari, using `SignalGroup` for the `DictEvents` rather than the napari event system
I removed a few little pieces that I wasn't sure about, namely
- child events
- `key` method on the dict
- the `update` event (changing/changed seem to cover the same cases)
Spent some time trying to please mypy too - typing is maybe starting to make some sense? 😆 I have likely made mistakes, please correct me if anything jumps out
> port `EventedDict` from napari

- src/psygnal/__init__.py
- src/psygnal/_signal.py
- tests/test_psygnal.py
closes #106 by raising all emit loop errors as a special `EmitLoopError` exception (RuntimeError) type:
@ianhi, this gives the decision on how to handle (or suppress) to the thing doing the emitting:
```python
from contextlib import suppress
from psygnal import EmitLoopError
with suppress(EmitLoopError):
obj.emitter.emit(...)
```
sound good?
> feat: raise exceptions as EmitLoopError

- pyproject.toml
cython 3.0.0a11 appears to be breaking builds.  pinning to 3.0.0a10 until I can investigate more
> build: pin cython

- src/psygnal/_group.py
- tests/test_group.py
This PR adds a `SignalGroup.disconnect()` method which behaves as `Signal.disconnect()` does but for all signals in the group.
I'm circling back to the Qt stuff we talked about a while ago and this would be super convenient in some cases there :-)
I realise this method is overloading `SignalInstance.disconnect()` so the behaviour may be unexpected... open to alternative names
> feat: Add ability to disconnect slots from Signal group directly

- src/psygnal/_evented_model.py
- tests/test_evented_model.py
This PR fixes __setattr__  in the EventedModel when called before initialization (e.g. in a subclass, before calling super().__init__())
> fix: fix bug in setattr with private attrs

- .pre-commit-config.yaml
- setup.py
- src/psygnal/__init__.py
- src/psygnal/_evented_decorator.py
- src/psygnal/_evented_model.py
- tests/test_evented_decorator.py
Psygnal already has the `EventedModel`, which is a somewhat "heavy" subclass of a pydantic's BaseModel.
This PR adds a much lighter-weight `@evented` decorator that will turn any dataclass into an evented-dataclass.  It currently supports `dataclasses.dataclass` from the standard library, `attrs.define` from attrs, and will also work when decorating a plain pydantic model (one which was not built using `psygnal.EventedModel` (the difference here is that using `psygnal.EventedModel` will _also_ add support for things like property.setters, _json_encoders, etc... whereas just decorating with `@evented` simply adds the events)
basic idea:
```python
from dataclasses import dataclass
from psygnal import evented
@evented
@dataclass
class Foo:
bar: int
baz: str
foo = Foo(bar=1, baz="2") …
```
> feat: add `@evented` decorator, turn any dataclass, attrs model, or pydantic model into evented

- src/psygnal/_evented_decorator.py
- tests/test_evented_decorator.py
adds a warning when `psygnal.evented` is used on a class that has no fields.
> feat: add warning for poor usage

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/psygnal/__init__.py
- src/psygnal/_signal.py
- src/psygnal/_throttler.py
- src/psygnal/containers/_evented_set.py
- tests/test_evented_model.py
adding back python 3.7 support.
I plan to follow [python's](https://devguide.python.org/versions/) end-of-life guides, rather than [numpy's](https://numpy.org/neps/nep-0029-deprecation_policy.html)
> build: support 3.7 again

- src/psygnal/_signal.py
- tests/test_psygnal.py
fixes #37 ... sorry for the long delay on this one @Czaki!
note that I made a slight adjustment to your test in that issue (that makes it a little less awesome, but still better):
```python
assert len(emitter.one_int) == 0
cb = partial(obj.f_int_int, 1) if slot == "partial" else getattr(obj, slot)
emitter.one_int.connect(cb)
assert len(emitter.one_int) == 1
emitter.one_int.emit(1)
assert len(emitter.one_int) == 1
emitter.one_int.disconnect(cb)
```
> fix: fix disconnection of partials

- .github/workflows/ci.yml
- pyproject.toml
- src/psygnal/_signal.py
- tests/test_psygnal.py
this catches failed weakref.ref() calls in connect_setattr, just like the ones in `connect_setitem` ... and adds a warning in both cases
> fix: fix failed weakref in connect_setattr

- setup.py
adds `install_requires` and name to `setup.py` for the sake of github dependency parsing
> chore: add deps to setup.py

- src/psygnal/_signal.py
- tests/test_psygnal.py
Signals are unblocked on exit of `blocked` context, which will cause problematic signal emission within nested contexts.
```python
from psygnal import Signal
class A:
sig = Signal(int)
a = A()
a.sig.connect(print)
with a.sig.blocked():
with a.sig.blocked():
a.sig.emit(0)
a.sig.emit(1)  # <----------- will be emitted
```
This PR fixes the problem above by checking if the signal is blocked first, and restore the original state on exit.
> Don't unblock/resume within nested contexts

- src/psygnal/_evented_model.py
makes it so that:
```py
class M(EventedModel):
x: int
```
shows a proper signature in VScode
> fix: add dataclass_transform to maintain IDE typing support for EventedModel.__init__

- docs/dataclasses.md
- pyproject.toml
- src/psygnal/_evented_decorator.py
- tests/test_evented_decorator.py
https://github.com/jcrist/msgspec is another fast library that implements a dataclass pattern.
this PR allows
```py
@evented
class Foo(msgspec.Struct):
bar: int
baz: str
qux: np.ndarray
```
since `Struct` is a c-extension with restrictions on overriding `__init__` and modifying `__slots__` this PR uses a new approach to create the SignalGroup on instances (using a descriptor on the class rather than a modified init)
> feat: add support for msgspec Struct classes to evented decorator

- src/psygnal/_signal.py
- tests/test_group.py
`SignalGroup` accepts an optional `instance` argument (the object to which it is bound).  This makes sure it's a weakref when possible
> fix: use weakref when instance is passed to SignalGroup

- src/psygnal/_signal.py
- tests/test_psygnal.py
This replaces some complicated internal logic for storing a weak reference to a bound method with [`weakref.WeakMethod`](https://docs.python.org/3/library/weakref.html#weakref.WeakMethod) ... it _seems_ like this is what should have been used all along?  @Czaki  ... would appreciate your thoughts if you have a moment to check
> refactor: use weakmethod instead of _get_method_name

- src/psygnal/_group.py
helps typing when you get an attribute on a signalgroup
> fix: add getattr to signalgroup for typing

- pyproject.toml
- src/psygnal/__init__.py
- src/psygnal/_evented_decorator.py
- src/psygnal/_evented_model.py
- src/psygnal/_group_descriptor.py
- tests/test_evented_decorator.py
this makes public the SignalGroupDescriptor used in the `evented` decorator.  
```python
from typing import ClassVar
from dataclasses import dataclass
from psygnal import SignalGroupDescriptor
@dataclass
class Foo:
bar: int
baz: str
events: ClassVar[SignalGroupDescriptor] = SignalGroupDescriptor()
foo = Foo(1, 'hi')
foo.events.bar.connect(print)
foo.bar = 2  # prints 2
```
all the decorator was really doing anyway was 1) setting that SignalGroupDescriptor() instance as a class attribute and 2) overriding __setattr__ with the evented version.  This now does that override when the signal group is first created (when the descriptor is accessed on the instance)
also, closes #172
> feat: public descriptor

- src/psygnal/_signal.py
Better preserves the typing information of a function decorated with `@...connect`
> fix: minor typing fixes on `connect`

- pyproject.toml
- src/psygnal/_dataclass_utils.py
- src/psygnal/_group_descriptor.py
- tests/test_dataclass_utils.py
this splits out the utilities that deal with generic dataclass flavors into its own module.  Might make it public
> refactor: split out dataclass utils

- .gitignore
- Makefile
- README.md
- docs/index.md
- src/psygnal/__init__.py
- src/psygnal/_evented_decorator.py
- src/psygnal/_group_descriptor.py
- src/psygnal/utils.py
- tests/test_group.py
- tests/test_psygnal.py
- tests/test_utils.py
the `PSYGNAL_UNCOMPILED` flag tries to allow the user to run psygnal in an uncompiled version by screwing with the import system. 
It's buggy and problematic.  This removes it and adds two utility functions `decompile` and `recompile`.  All they do is rename the `.so`/`.pyd` files so as to make them unusuable/usable.
> refactor: remove PSYGNAL_UNCOMPILED flag.

- src/psygnal/utils.py
- tests/test_utils.py
skip coverage on the decompile/recompile utility functions (they're tested, but difficult for coverage)
> test: no cover compile funcs

- src/psygnal/_group_descriptor.py
- tests/test_group_descriptor.py
signals were getting pinned to the base class after #173, and inheritance wasn't working.  This fixes and adds a test
> fix: fix inheritance of classes with a SignalGroupDescriptor

- docs/dataclasses.md
- src/psygnal/_group_descriptor.py
- tests/test_evented_decorator.py
- tests/test_group_descriptor.py
adding `SignalGroupDescriptor` as a class attribute will patch the class's `__setattr__` method (on the first access of the descriptor on an instance).  This PR:
1. changes the moment when that patching occurs
2. provides an opt-out mechanism (in which case the user must patch `__settattr__` themselves)
3. documents it more obviously
4. uses a cleaner context manager within the `evented_setattr` pattern
> refactor: change patching of __setattr__ in SignalGroupDescriptor, make more explicit

- benchmarks/_evented.py
- docs/dataclasses.md
- tests/test_bench.py
adding benchmarks to time the creation of evented dataclasses, and time to setattr
> ci: add dataclasses benchmarks

- src/psygnal/_group.py
- src/psygnal/_signal.py
- tests/test_group.py
> fix: fix strict signal group checking when signatures aren't hashable

- pyproject.toml
- src/psygnal/_pyinstaller_util/_pyinstaller_hook.py
- src/psygnal/_pyinstaller_util/hook-psygnal.py
- src/psygnal/_pyinstaller_util/test_pyinstaller_hook.py
- tests/test_pyinstaller_hook.py
see https://github.com/pyapp-kit/psygnal/issues/162#issuecomment-1446344343
I have created code to automatically add every `.so`, `pyd` file to hidden imports. 
It is a little complicated but reduces maintenance. Maybe I should just hardcode the list?
> build: add pyinstaller hook to simplify frozing apps using pyinstaller 

- pyproject.toml
- src/psygnal/__init__.py
- src/psygnal/_exceptions.py
- src/psygnal/_pyinstaller_util/hook-psygnal.py
- src/psygnal/_queue.py
- src/psygnal/_signal.py
- src/psygnal/qt.py
- tests/test_psygnal.py
- tests/test_pyinstaller_hook.py
- tests/test_qt_compat.py
- tests/test_weak_callable.py
alternative to #199  ... hat-tip to @Czaki  for the inspiration.
somewhat closer to realizing #198 
run this script as an example
```python
import threading
from qtpy.QtWidgets import QApplication
from psygnal import Signal
from psygnal.qt import start_emitting_from_queue 
class Emitter:
sig = Signal(int)
obj = Emitter()
@obj.sig.connect(thread='main')
def on_emit(value: int) -> None:
"""Callback function that states its thread."""
print(f"got value {value} from thread {threading.current_thread().name!r}")
app = QApplication([])
start_emitting_from_queue()
threading.Thread(target=obj.sig.emit, args=(1,)).start()
app.processEvents()
```
> feat: add thread parameter to connection method, allowed "queued connections"

- docs/usage.md
- mkdocs.yml
- src/psygnal/_signal.py
- tests/test_psygnal.py
with #200 as  the preferred approach for dealing with signals across threads, this deprecates the `asynchronous` keyword to `emit.`
> chore: deprecate async keyword in emit method

- src/psygnal/_signal.py
- tests/test_psygnal.py
it's possible using `functools.partials` to create required keyword-only arguments without paying attention:
```py
def f(a, b): ...
f2 = partial(f, a=1)  # b is now a required keyword argument
```
```pytb
In [5]: f2(3)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 f2(3)
TypeError: f() got multiple values for argument 'a'
```
These are particularly hard for a callback system, and aren't currently supported by psygnal.  This PR just makes the error message a bit clearer if the user stumbles into this use case
> fix: better error message with keyword only partials

- .github/workflows/test.yml
- pyproject.toml
- src/psygnal/__init__.py
- src/psygnal/_dataclass_utils.py
- src/psygnal/_evented_model_v1.py
- src/psygnal/_evented_model_v2.py
- src/psygnal/_group_descriptor.py
- tests/test_dataclass_utils.py
- tests/test_evented_decorator.py
- tests/test_evented_model.py
- tests/test_pyinstaller_hook.py
This PR unpins the pydantic extra, and adds support for pydantic v2.
it does so in a relatively ugly way, by simply copying the whole `evented_model` module and importing one or the other depending on which version of pydantic we have... there's a lot of code dupe.  but it's a pretty stable module at this point, so keeping them in sync shouldn't be hard (particularly with all the tests).  So I'm not gonna bother deduplicating
> feat: support pydantic v2

- pyproject.toml
- src/psygnal/_throttler.py
- tests/test_throttler.py
in [mypyc's words](https://mypyc.readthedocs.io/en/latest/differences_from_python.html#introspection): "`inspect.signature` chokes on compiled functions"... which is a bummer for throttled/debounced if we're going to use them as callbacks (which is their main goal).
This PR fixes https://github.com/napari/napari/issues/6149#issuecomment-1678081559 by telling inspect.signature how to get to the wrapped function.  I think it should be good enough, but if more problems arise, we can just skip mypyc compilation on these modules.
cc @andy-sweet
*edit*: i just decided not to compile that module for now.
> fix: fix signature inspection on debounced/throttled, update typing and wrapped

- src/psygnal/containers/_evented_dict.py
- src/psygnal/containers/_evented_list.py
- src/psygnal/containers/_evented_set.py
- tests/containers/test_evented_dict.py
- tests/containers/test_evented_list.py
- tests/containers/test_evented_set.py
closes #254
This PR fixes copy of EventedSet and add copy operator to EventedList and EventedDic.
> fix: add and fix copy operators

- src/psygnal/_group_descriptor.py
- src/psygnal/_signal.py
- tests/test_group_descriptor.py
This is a patch that will help #257: it sets the default `maxargs` to `1` for the `setattr_method` of all `SignalInstance` created in evented dataclasses.  this is probably the expected behavior anyway, since all signals on an evented dataclass usually emit only the value of that field
> fix: fix connect_setattr on dataclass field signals

- src/psygnal/_evented_decorator.py
- src/psygnal/_group_descriptor.py
- tests/test_bench.py
- tests/test_evented_decorator.py
- tests/test_group_descriptor.py
I'm using `SignalGroupDescriptor` (or `evented`) with an `attrs` dataclass and I would like the change signal to emit the old value alongside the new value when mutated. 
It's a minimal change to allow that, in `_evented_decorator._changes_emitted` method `__exit__`, just change:
`self.signal.emit(new)`  --> `self.signal.emit(new, self._prev)`
I put the old value in second place because it should allow to connect to slots defined with only the new value as argument.
However, in order to not be a disturbing change, it would be better if it is opt-in.
That is this PR. It is working, but not with subclassing.
Any idea?
```python
import numpy as np
from psygnal import evented, Signal, EmissionInfo
from attrs import asdict, define, make_class, Factory, field, cmp_using …
```
> feat: emit the old value as second argument in Signals from SignalGroupDescriptor (evented dataclass)

- src/psygnal/_group_descriptor.py
- src/psygnal/_signal.py
- tests/test_bench.py
- tests/test_psygnal.py
See #257 for some discussion, the default behavior of `connect_setattr` and `connect_setitem` is going to change in v0.11:
Both of these methods are really designed/intended for callbacks that expect a single value, but the current behavior, when dealing with a signal that emits two values, is to combine those two values into a tuple.  Meaning if the signal changes from a single argument to 2 arguments (as happened in #257), then the value received by the callback changes from a singleton type to a tuple.   This makes it much harder to change the emission signatures in a non-breaking way, which is *otherwise* designed to be rather easy to do (since it's ok to connect a signal to a callback that takes less arguments than the signal emits). 
This PR adds a `FutureWarning` to …
> chore: add future warning for maxargs in connect_setattr/setitem

- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- src/psygnal/_dataclass_utils.py
- src/psygnal/_evented_decorator.py
- src/psygnal/_evented_model_v1.py
- src/psygnal/_evented_model_v2.py
- src/psygnal/_group.py
- src/psygnal/_group_descriptor.py
- src/psygnal/_mypyc.py
- src/psygnal/_queue.py
- src/psygnal/_signal.py
- src/psygnal/_throttler.py
- src/psygnal/_throttler.pyi
- src/psygnal/_weak_callback.py
- src/psygnal/containers/_evented_set.py
- tests/test_evented_model.py
- tests/test_group.py
- tests/test_psygnal.py
- tests/test_qt_compat.py
This PR removes `mypy_extensions` and `typing-extensions` from the dependencies.  Neither are required at runtime.  all use of typing-extensions is guarded behind TYPE_CHECKING imports, and mypy_extensions is only required at build time (in fact, it's not even needed at all, it seems you can just put `from mypy_extensions import mypyc_attr` inside of a try/except and that is sufficient) but it's included at build time anyway
it also moves some of the older type hint imports from typing-extensions to typing
> build: remove all dependencies

- src/psygnal/_evented_model_v1.py
- src/psygnal/_evented_model_v2.py
- src/psygnal/_group.py
- src/psygnal/_group_descriptor.py
- src/psygnal/_signal.py
- tests/test_group.py
- tests/test_psygnal.py
> perf: Delay SignalRelay connection to when a callback is connected

- src/psygnal/_evented_model_utils.py
- src/psygnal/_evented_model_v1.py
- src/psygnal/_evented_model_v2.py
- tests/test_evented_model.py
This PR migrates https://github.com/napari/napari/pull/6075 into psygnal to deduplicated event emission.
This will allow in future to drop the `napari.utils.events` module.
> feat: deduplicate events emision in nested properties

- docs/usage.md
- src/psygnal/_signal.py
- tests/test_psygnal.py
- typesafety/test_signal.yml
`emit(asynchronous=True)` has been depreacted for a year now.  This removes it along with some other old deprecations.
> chore: remove asynchronous emit and other deprecations

- src/psygnal/containers/_evented_dict.py
- src/psygnal/containers/_evented_list.py
- src/psygnal/containers/_evented_set.py
- tests/test_pydantic_support.py
This is in support of #252, where I [noted](https://github.com/pyapp-kit/psygnal/issues/252#issuecomment-1892963254) that evented containers don't work well as fields for pydantic models.  Specifically, this enables:
```python
class Model(pydantic.BaseModel):
my_list: psygnal.containers.EventedList[int]  # or other evented containers
```
This only supports pydantic v2 (for now, and probably forever), since pydantic v1 always had very bad support for custom Generic fields
> feat: support for evented containers as pydantic v2 fields

- src/psygnal/_signal.py
- tests/test_psygnal.py
- tests/test_weak_callable.py
adds basic test for recursion error as discovered/mentioned in https://github.com/Czaki/psygnal/pull/1
> test: test for recursion error

- src/psygnal/_group.py
- src/psygnal/_group_descriptor.py
- src/psygnal/_queue.py
- src/psygnal/_signal.py
- src/psygnal/_weak_callback.py
- tests/test_psygnal.py
This adds the ability to control the order in which callbacks are called at connection time.  Higher priority connections are called first, and negative priorities are allowed.  with default 0
```python
sig = SignalInstance()
calls = []
sig.connect(lambda: calls.append(1))
sig.connect(lambda: calls.append(2), priority=5)
sig.connect(lambda: calls.append(3), priority=-5)
sig.connect(lambda: calls.append(4), priority=10)
sig.emit()
assert calls == [4, 2, 1, 3]
```
> feat: add priority to connect, to control callback order

- src/psygnal/_group.py
- src/psygnal/_signal.py
- tests/test_evented_model.py
couple minor changes before releasing v0.10.0
this removes the deprecation of SignalGroup.signals, delaying the decision for a later version
> chore: un-deprecate SignalGroup.signals

- .github/workflows/benchmark.yml
- Makefile
- asv.conf.json
- pyproject.toml
this is an ugly fix to deal with the fact that hatchling doesn't respect MACOSX_DEPLOYMENT_TARGET, and when I try to run asv benchmarks locally, the wheel that gets created is doesn't get interpreted as compatible with the system, and can't be installed.  One fix is to set `macos-max-compat = false` in the hatch wheel settings, but I only want that to happen when benchmarking locally, and that setting doesn't seem to be switchable by an environment variable.  so this is the unfortunate solution I came up with.  
inspired by black's pyproject: https://github.com/psf/black/blob/6af7d1109693c4ad3af08ecbc34649c232b47a6d/pyproject.toml
> chore: patch asv config to work locally with arm64 macos on hatchling

- src/psygnal/_exceptions.py
- src/psygnal/_signal.py
- tests/test_psygnal.py
fixes #300 
I'm working on a better fix that would avoiding holding even a temporary pointer to the arguments, but want to get this fix out asap
> fix: fix hard reference to objects in emitted arguments

- CHANGELOG.md
- src/psygnal/__init__.py
- src/psygnal/_evented_decorator.py
- src/psygnal/_group.py
- src/psygnal/_group_descriptor.py
- tests/test_evented_model.py
- tests/test_group.py
- tests/test_group_aliases.py
Split from #265
solves https://github.com/pyapp-kit/psygnal/issues/261
Add a keyword argument to `SignalGroupDescriptor` to specify signal aliases (if the alias is None, no signal is created for this field). The signal aliases table is stored in the `SignalGroup` class (or subclass).
> feat: add signal aliases on SignalGroup

- src/psygnal/_evented_model.py
- src/psygnal/_signal.py
- src/psygnal/containers/_evented_dict.py
- src/psygnal/containers/_evented_list.py
- src/psygnal/containers/_evented_set.py
- tests/test_evented_model.py
- tests/test_psygnal.py
This PR renames the parameter controlling how callbacks are (re-)invoked when one of the callbacks itself emits the signal currently being emitted.  From the new docstrings:
```
reemission : Literal["immediate", "queued", "latest-only"] | None
Determines the order and manner in which connected callbacks are invoked when a
callback re-emits a signal. Default is `"immediate"`.
```
* `"immediate"`: Signals emitted by callbacks are immediately processed in a
deeper emission loop, before returning to process signals emitted at the
current level (after all callbacks in the deeper level have been called).
* `"queued"`: Signals emitted by callbacks are enqueued for emission after the
current level of emission is complete. This ensures *all* connected
callbacks are called with the first emitted …
> feat: Rename `recursion_mode` to `reemission`.  Rename `deferred` to `queued`.  Add `latest-only` mode.

- src/psygnal/_exceptions.py
- src/psygnal/_queue.py
- src/psygnal/_signal.py
- tests/test_psygnal.py
- tests/test_weak_callable.py
This PR avoids the need to hang on to any information about the current callback & args by inspecting the stack after an exception happens.  I think it also makes the error a bit easier to read.
With the following error as an example:
```python
from psygnal import SignalInstance
sig = SignalInstance((int,), name="sig")
@sig.connect
def some_func(x: int) -> None:
print(1 / x)
sig.emit(0)
```
before this PR:
```pytb
psygnal._exceptions.EmitLoopError:
While emitting signal 'builtins.NoneType.sig', an error occurred in callback '__main__.some_func'.
The args passed to the callback were: (0,)
This is not a bug in psygnal.  See 'ZeroDivisionError' above for details.
```
after this PR:
```pytb
psygnal.EmitLoopError:
While emitting signal "<SignalInstance 'sig'>", an error occurred in a callback: …
```
> refactor: change EmitLoopError message, and mechanism of info gathering

- benchmarks/benchmarks.py
- src/psygnal/containers/_evented_set.py
Motivated by https://github.com/napari/napari/issues/6746, https://github.com/napari/napari/pull/6895
The default `clear` method implemented by `collections.abc.MutableSet` is very slow, which I guess is due to the fact that it is not backed by the C implementation of the builtin `set`. 
I have attempted to implement a custom interface for `clear`, modelled on the existing one for `discard`. However, I don't entirely understand the intentions for the various hooks, BAILs, etc, so please do let me know if anything is inconsistent with the behaviours and styles of other methods.
bench.py
```python
from psygnal.containers import EventedSet
num = 100_000
my_set = EventedSet(range(num))
my_set.events.items_changed.connect(print)
my_set.clear()
```
Before:
```cmd
> hyperfine --warmup 1 …
```
> perf: let EventedSet use clear() method of underlying set

- .github/workflows/pypi.yml
- .github/workflows/test.yml
- pyproject.toml
Some CI maintenance:
- Update the Pypi.yml host OSes to their latest compatible versions
- Add Python 3.13 to the test matrix.
- This needs https://github.com/pyapp-kit/workflows/pull/10
> CI: Update host OS version, add Python 3.13

- benchmarks/benchmarks.py
- src/psygnal/_signal.py
- tests/test_bench.py
- tests/test_psygnal.py
This PR is in response to @beniroquai's https://github.com/pyapp-kit/psygnal/issues/330#issuecomment-2436321438:
> but the frame-rate drops significantly in the psygnal case
Indeed, the compiled version of psygnal is roughly 5 times slower than Qt (the uncompiled version is about 6.5-7 times slower).  It looks like all that slowdown comes from safety mechanisms and other "features" that may not be used in many cases, (like the ability to query the sender, etc...).  So, this PR adds a stripped down `emit_fast()` method that has the following changes:
- It does not support `check_nargs` or `check_types`
- It does not use any thread safety locks.
- It is not possible to query the emitter with `Signal.current_emitter()`
- It is not possible to query the sender with `Signal.sender()`
- It does …
> fast: add `emit_fast` method for 10x faster emission (without safety checks)

- src/psygnal/_evented_model.py
`property_dependencies` was renamed to `field_dependencies` in https://github.com/pyapp-kit/psygnal/pull/234 but some associated error messages and docs still refer to the deprecated name.
> Update EventedModel docs and errors to refer `field_dependencies`

- src/psygnal/_evented_model.py
- tests/test_evented_model.py
> fix: fix use of computed_field setter with field_dependencies

- src/psygnal/_signal.py
- tests/test_psygnal.py
> feat: add description to signalinstance

- docs/index.md
Adding a while loop to the index.md example with the ability to show what happens with looping, seeing multiple signals sent and handled, seeing the changed print statements when the signals are handled, when the inputs are changed and signals emitted.
example tested with python 3.9+ python on macos
> docs: modified quickstart simple example

- asv.conf.json
- src/psygnal/_exceptions.py
yet another update to how the emit loop error exception looks.  with this PR it will now look something like this:
```pytb
While emitting signal 'ndv.models._mapping.ValidatedEventedDict.value_changed', an error occurred in a callback:
ValueError: Dimensions {0, 1, 2} do not exist. Expected one or more of ('time', 'lat', 'lon')
---------------------------------------------------------------------------------------------
SIGNAL EMISSION: 
/Users/talley/dev/self/ndv/src/ndv/controllers/_array_viewer.py:302 in _on_view_current_index_changed
self._data_model.display.current_index.update(self._view.current_index())
/Users/talley/dev/self/ndv/src/ndv/models/_mapping.py:187 in update
self.value_changed.emit()  # <-- SIGNAL WAS EMITTED HERE
CALLBACK CHAIN: …
```
> refactor: update exception message

- src/psygnal/_weak_callback.py
I found an edge case when trying to connect to a slot, where that slot itself had a recursion error in its `__repr__` method, where the entire connection failed with a recursion error in what should have been a simple warning when the slot was not weak-refable.  This PR uses `object.__repr__(object)` instead of `repr(object)`, just in case the object in question in un-reprable
> fix: use safer repr in warning

- src/psygnal/_evented_model.py
Pydantic 2.11 has deprecated accessing model_fields from instances of the model class, instead requiring callers to use the class itself.
Fixes #356
> Don't use deprecated model_fields access

- docs/guides/testing.md
- mkdocs.yml
- src/psygnal/testing.py
- tests/test_testing_utils.py
closes #46 (i think?  @Czaki?) by adding conveniences around testing with psygnal.
These are all synchronous tests, so they don't do anything like `waitSignal()` ... note that you can already *also* use `pytestqt` to call `waitSignal()` and wait for a psygnal Signal.  But this just removes a lot of boilerplate to test standard scenarios without having to use `Mock()`
```python
from psygnal import Signal
import psygnal.testing as pt
class MyObject:
changed = Signal()
value_changed = Signal(int)
def test_my_object():
obj = MyObject()
with pt.assert_emitted(obj.changed):
obj.changed.emit()
with pt.assert_not_emitted(obj.value_changed):
obj.changed.emit()
with pt.assert_emitted_once(obj.value_changed):
obj.value_changed.emit(42)
with pt.assert_emitted_once_with(obj.value_changed, 42): …
```
> feat: add testing utilities

- pyproject.toml
- src/psygnal/testing.py
makes it clear that `SignalTester` accepts either a SignalInstance, and doesn't compile that module with mypyc (unnecessary and can cause problems)
> fix: fix typing in psygnal testing
